---
output: github_document
---

# *K*~OA~ Database
**Last Updated: Sept 22 2021**

This package contains the *K*~OA~ database presented in *[Baskaran et al. 2021](https://www.doi.org/10.1063/5.0059652)*. All data obtained from the current version of the database (ver. 1) should be cited as: Baskaran, S., Lei, Y.D., Wania, F., "Reliable prediction of the octanol-air partition ratio," *Journal of Physical and Chemical Reference Data* (2021). https://doi.org/10.1063/5.0059652 

This database contains experimental and estimated *K*~OA~ values that we could identify in the literature including those from PhD dissertations. Information in this database includes the identity of the chemical for which the *K*~OA~ is reported, the temperature of the value, the methodology used, the original citation and a score on the quality of data.

By default the latest version of the database is called by the functions. Currently there is only one version of the database. For more information on how to use the database [click here](https://sivanibaskaran.github.io/koadata/).

This database is complete to the best of our knowledge as of May 2021. A few papers with *K*~OA~ values (experimental or estimated) have been published since this time:

1. Feng, J.-J., Sun, X.-F., Zeng, E.Y., "Measurement of octanol–air partition coefficients for liquid crystals based on gas chromatography-retention time and its implication in predicting long-range transport potential," *Chemosphere* **282**, 131109 (2021). https://doi.org/10.1016/j.chemosphere.2021.131109

2. Abraham, M.H., Acree, W.E., "Descriptors for fluorotelomere alcohols. Calculation of physicochemical properties," *Physics and Chemistry of Liquids* 1–6 (2021). https://doi.org/10.1080/00319104.2021.1888094

3. Baskaran, S., Lei, Y.D., Wania, F., "Reliable prediction of the octanol-air partition ratio," *Environmental Chemistry & Toxicology* (2021). https://doi.org/10.1002/etc.5201 


If you are aware of additional work which includes either experimental or estimated *K*~OA~ values published in the literature please let us know using this [link](https://forms.gle/u38fENZoAtixvM8G9).

